<a href="https://colab.research.google.com/github/RelaxingCoyote/NEUROEV/blob/main/NCL_Khayrov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Нейроэволюционные вычисления

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1-EpdWG47AK3_W6bAYBrHNKM6vCYej-O3#scrollTo=MSdEKikMh9kf)

Подключаем гугл-диск.

In [1]:
from google.colab import drive
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive


Устанавливаем пакет Datatable.

In [2]:
pip install datatable

Импортируем необходимые библиотеки.

In [3]:
import datatable as dt
print(dt.__version__)

0.11.1


Загружаем набор данных.

In [4]:
DT = dt.fread('/content/gdrive/MyDrive/Machine Learning/NEUROEV/cancer1.dt')
DT

    | C0                         C1    C2    C3    C4    C5    C6    C7    C8  C9  C10
--- + -----------------------  ----  ----  ----  ----  ----  ----  ----  ----  --  ---
  0 | bool_in=0                NA    NA    NA    NA    NA    NA    NA    NA    NA   NA
  1 | real_in=9                NA    NA    NA    NA    NA    NA    NA    NA    NA   NA
  2 | bool_out=2               NA    NA    NA    NA    NA    NA    NA    NA    NA   NA
  3 | real_out=0               NA    NA    NA    NA    NA    NA    NA    NA    NA   NA
  4 | training_examples=350    NA    NA    NA    NA    NA    NA    NA    NA    NA   NA
  5 | validation_examples=175  NA    NA    NA    NA    NA    NA    NA    NA    NA   NA
  6 | test_examples=174        NA    NA    NA    NA    NA    NA    NA    NA    NA   NA
  7 | 0.2                       0.1   0.1   0.1   0.2   0.1   0.2   0.1   0.1   1    0
  8 | 0.2                       0.1   0.1   0.1   0.2   0.1   0.3   0.1   0.1   1    0
  9 | 0.5                       0.1   0.1  

C0 C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 
 ▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪ ▪ 
 
 
 0 bool_in=0 NA NA NA NA NA NA NA NA NA NA 
 1 real_in=9 NA NA NA NA NA NA NA NA NA NA 
 2 bool_out=2 NA NA NA NA NA NA NA NA NA NA 
 3 real_out=0 NA NA NA NA NA NA NA NA NA NA 
 4 training_examples=350 NA NA NA NA NA NA NA NA NA NA 
 5 validation_examples=175 NA NA NA NA NA NA NA NA NA NA 
 6 test_examples=174 NA NA NA NA NA NA NA NA NA NA 
 7 0.2 0.1 0.1 0.1 0.2 0.1 0.2 0.1 0.1 1 0 
 8 0.2 0.1 0.1 0.1 0.2 0.1 0.3 0.1 0.1 1 0 
 9 0.5 0.1 0.1 0.1 0.2 0.1 0.2 0.1 0.1 1 0 
 10 0.5 0.4 0.6 0.8 0.4 0.1 0.8 1 0.1 0 1 
 11 0.5 0.3 0.3 0.1 0.2 0.1 0.2 0.1 0.1 1 0 
 12 0.2 0.3 0.1 0.1 0.3 0.1 0.1 0.1 0.1 1 0 
 13 0.3 0.5 0.7 0.8 0.8 0.9 0.7 1 0.7 0 1 
 14 1 0.5 0.6 1 0.6 1 0.7 0.7 1 0 1 
 ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ 
 701 0.5 0.1 0.2 0.1 0.2 0.1 0.1 0.1 0.1 1 0 
 702 0.7 0.5 0.6 1 0.5 1 0.7 0.9 0.4 0 1 
 703 0.6 1 1 1 0.8 1 0.7 1 0.7 0 1 
 704 0.5 0.7 1 1 0.5 1 1 1 0.1 0 1 
 705 0.1 0.1 0.1 0.1 0.2 0.1 0.2 0.1 0.1 1 0 
 
 
 
 706 rows × 11 columns

Очистим набор данных от лишних столбцов.

In [5]:
del DT[0:7,:]
DT

    | C0    C1   C2   C3   C4   C5   C6   C7   C8  C9  C10
--- + ---  ---  ---  ---  ---  ---  ---  ---  ---  --  ---
  0 | 0.2  0.1  0.1  0.1  0.2  0.1  0.2  0.1  0.1   1    0
  1 | 0.2  0.1  0.1  0.1  0.2  0.1  0.3  0.1  0.1   1    0
  2 | 0.5  0.1  0.1  0.1  0.2  0.1  0.2  0.1  0.1   1    0
  3 | 0.5  0.4  0.6  0.8  0.4  0.1  0.8  1    0.1   0    1
  4 | 0.5  0.3  0.3  0.1  0.2  0.1  0.2  0.1  0.1   1    0
  5 | 0.2  0.3  0.1  0.1  0.3  0.1  0.1  0.1  0.1   1    0
  6 | 0.3  0.5  0.7  0.8  0.8  0.9  0.7  1    0.7   0    1
  7 | 1    0.5  0.6  1    0.6  1    0.7  0.7  1     0    1
  8 | 1    0.9  0.8  0.7  0.6  0.4  0.7  1    0.3   0    1
  9 | 0.4  0.1  0.1  0.1  0.2  0.1  0.3  0.1  0.1   1    0
 10 | 0.5  0.1  0.1  0.1  0.2  0.1  0.3  0.1  0.1   1    0
 11 | 0.8  1    1    0.1  0.3  0.6  0.3  0.9  0.1   0    1
 12 | 0.1  0.1  0.3  0.1  0.2  0.1  0.2  0.1  0.1   1    0
 13 | 0.1  0.1  0.1  0.2  0.1  0.1  0.1  0.1  0.1   1    0
 14 | 0.3  0.4  0.5  0.2  0.6  0.8  0.4  0.1  0.1   0   

C0 C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 
 ▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪▪▪▪▪▪▪▪ ▪ ▪ 
 
 
 0 0.2 0.1 0.1 0.1 0.2 0.1 0.2 0.1 0.1 1 0 
 1 0.2 0.1 0.1 0.1 0.2 0.1 0.3 0.1 0.1 1 0 
 2 0.5 0.1 0.1 0.1 0.2 0.1 0.2 0.1 0.1 1 0 
 3 0.5 0.4 0.6 0.8 0.4 0.1 0.8 1 0.1 0 1 
 4 0.5 0.3 0.3 0.1 0.2 0.1 0.2 0.1 0.1 1 0 
 5 0.2 0.3 0.1 0.1 0.3 0.1 0.1 0.1 0.1 1 0 
 6 0.3 0.5 0.7 0.8 0.8 0.9 0.7 1 0.7 0 1 
 7 1 0.5 0.6 1 0.6 1 0.7 0.7 1 0 1 
 8 1 0.9 0.8 0.7 0.6 0.4 0.7 1 0.3 0 1 
 9 0.4 0.1 0.1 0.1 0.2 0.1 0.3 0.1 0.1 1 0 
 10 0.5 0.1 0.1 0.1 0.2 0.1 0.3 0.1 0.1 1 0 
 11 0.8 1 1 0.1 0.3 0.6 0.3 0.9 0.1 0 1 
 12 0.1 0.1 0.3 0.1 0.2 0.1 0.2 0.1 0.1 1 0 
 13 0.1 0.1 0.1 0.2 0.1 0.1 0.1 0.1 0.1 1 0 
 14 0.3 0.4 0.5 0.2 0.6 0.8 0.4 0.1 0.1 0 1 
 ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ ⋮ 
 694 0.5 0.1 0.2 0.1 0.2 0.1 0.1 0.1 0.1 1 0 
 695 0.7 0.5 0.6 1 0.5 1 0.7 0.9 0.4 0 1 
 696 0.6 1 1 1 0.8 1 0.7 1 0.7 0 1 
 697 0.5 0.7 1 1 0.5 1 1 1 0.1 0 1 
 698 0.1 0.1 0.1 0.1 0.2 0.1 0.2 0.1 0.1 1 0 
 
 
 
 699 rows × 11 columns

Представим набор данных в виде DataFrame Pandas.

In [6]:
import pandas as pd
df = pd.DataFrame(DT.to_pandas())
df

C0   C1   C2   C3   C4   C5   C6   C7   C8     C9    C10
0    0.2  0.1  0.1  0.1  0.2  0.1  0.2  0.1  0.1   True  False
1    0.2  0.1  0.1  0.1  0.2  0.1  0.3  0.1  0.1   True  False
2    0.5  0.1  0.1  0.1  0.2  0.1  0.2  0.1  0.1   True  False
3    0.5  0.4  0.6  0.8  0.4  0.1  0.8  1.0  0.1  False   True
4    0.5  0.3  0.3  0.1  0.2  0.1  0.2  0.1  0.1   True  False
..   ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...
694  0.5  0.1  0.2  0.1  0.2  0.1  0.1  0.1  0.1   True  False
695  0.7  0.5  0.6  1.0  0.5  1.0  0.7  0.9  0.4  False   True
696  0.6  1.0  1.0  1.0  0.8  1.0  0.7  1.0  0.7  False   True
697  0.5  0.7  1.0  1.0  0.5  1.0  1.0  1.0  0.1  False   True
698  0.1  0.1  0.1  0.1  0.2  0.1  0.2  0.1  0.1   True  False

[699 rows x 11 columns]

Разобъём выборку на тестовую и тренировочную.

In [7]:
y = df[['C9','C10']]
y

C9    C10
0     True  False
1     True  False
2     True  False
3    False   True
4     True  False
..     ...    ...
694   True  False
695  False   True
696  False   True
697  False   True
698   True  False

[699 rows x 2 columns]

In [8]:
X = df.iloc[:, 0:9].copy()
X

C0   C1   C2   C3   C4   C5   C6   C7   C8
0    0.2  0.1  0.1  0.1  0.2  0.1  0.2  0.1  0.1
1    0.2  0.1  0.1  0.1  0.2  0.1  0.3  0.1  0.1
2    0.5  0.1  0.1  0.1  0.2  0.1  0.2  0.1  0.1
3    0.5  0.4  0.6  0.8  0.4  0.1  0.8  1.0  0.1
4    0.5  0.3  0.3  0.1  0.2  0.1  0.2  0.1  0.1
..   ...  ...  ...  ...  ...  ...  ...  ...  ...
694  0.5  0.1  0.2  0.1  0.2  0.1  0.1  0.1  0.1
695  0.7  0.5  0.6  1.0  0.5  1.0  0.7  0.9  0.4
696  0.6  1.0  1.0  1.0  0.8  1.0  0.7  1.0  0.7
697  0.5  0.7  1.0  1.0  0.5  1.0  1.0  1.0  0.1
698  0.1  0.1  0.1  0.1  0.2  0.1  0.2  0.1  0.1

[699 rows x 9 columns]

In [9]:
from sklearn.model_selection import train_test_split

y_train,y_test,X_train,X_test = train_test_split(y,X,train_size = 0.8, random_state = 3)

Добавим сигмоидальную функцию активации.

In [10]:
import numpy as np

def sigmoid(x):
  s = np.array(x)
  s = 1/(1+np.exp(-s))
  return s

Зададим класс нейронной сети.

In [11]:
# Класс находится в разработке
# bcgjkm
class NN:
  
  def __init__(self, hidden_layers=None, hidden_nodes =None):
    # Веса нейронных связей
    self.w = None
    # Смещение нейрона (bias)
    self.b = None
    if hidden_layers >1:
      self.w = np.random.rand(hidden_layers-1,hidden_nodes,hidden_nodes)
      
    if hidden_layers >=1:
      self.b = np.random.uniform(low=-0.2, high=0.2, size=(hidden_layers,hidden_nodes))
    
    # матрица внутренних нейронов имеет прямоугольный вид
    hidden_neurons = np.zeros((hidden_layers,hidden_nodes))
    
  # двумерный fit
  def fit(self,X,y):
    self.input = np.zeros_like(X[-1])
    self.output = np.zeros_like(y[-1])

  def print_weights(self):
    print(self.w)

  def print_bias(self):
    print(self.b)
    

In [12]:
neur= NN(hidden_layers=2, hidden_nodes =3)

neur.print_weights()
neur.print_bias()

[[[0.58353706 0.45232602 0.47237068]
  [0.62696073 0.15470219 0.81289673]
  [0.07532212 0.52254819 0.07639404]]]
[[ 0.10908102  0.09972765 -0.11211692]
 [ 0.14517571  0.12241372 -0.15586408]]
